# Example config for training with ResNet-18
dataset:
  images_dir: /home/e1444/repos/mammograph/data/vindr-mammo/1.0.0/images
  annotations_file: /home/e1444/repos/mammograph/data/vindr-mammo/1.0.0/breast-level_annotations.csv
  view: CC
  train_split: training
  val_split: test
  auto_labels: auto
  label_map_file: null
  label_values: null
  use_class_weights: true

model:
  name: resnet18
  num_classes: 5
  pretrained: true
  in_channels: 1
  freeze_backbone: false

training:
  image_size: 224
  batch_size: 16
  epochs: 20
  device: auto
  save_dir: outputs/checkpoints/resnet18
  workers: 4

optimizer:
  name: Adam
  lr: 1e-3

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: ${training.epochs}

wandb:
  use: true
  project: vindr-mammograph
  entity: e1444-university-of-toronto
  run_name: resnet18-experiment
